INSERT INTO TODO (USER_NAME, DESCRIPTION, TARGET_DATE, DONE)
    VALUES ('admin', 'Learn Spring MVC', '2019-10-10', false);
INSERT INTO TODO (USER_NAME, DESCRIPTION, TARGET_DATE, DONE)
    VALUES ('admin', 'Learn Struts', '2019-10-10', false);
INSERT INTO TODO (USER_NAME, DESCRIPTION, TARGET_DATE, DONE)
    VALUES ('admin', 'Learn Hibernate', '2019-10-10', false);
INSERT INTO TODO (USER_NAME, DESCRIPTION, TARGET_DATE, DONE)
    VALUES ('admin', 'Learn Spring Security', '2019-10-10', false);
INSERT INTO TODO (USER_NAME, DESCRIPTION, TARGET_DATE, DONE)
    VALUES ('admin', 'Learn AOP', '2019-10-10', false);